# Generated by Django 3.0.8 on 2020-07-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20200714_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albumcover',
            field=models.ImageField(blank=True, null=True, upload_to='media/album/images/'),
        ),
    ]
